[build]
  command = "node assets/js/generate-sitemaps.js --base https://aiporndirect.com || true"
  publish = "."

[[redirects]]
  from = "http://aiporndirect.com/*"
  to = "https://aiporndirect.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.aiporndirect.com/*"
  to = "https://aiporndirect.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
